drop table if exists film cascade;

create table director
(
    id         int8 generated by default as identity,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    birth_date date         not null,
    primary key (id)
);

create table film
(
    id           int8 generated by default as identity,
    director_id  int8,
    name         varchar(255),
    release_date date,
    genre        varchar(255),
    primary key (id)
);

alter table if exists film
    add constraint film_director_fk foreign key
        (director_id) references director